### ISSUE TITLE
Plugin "tiny_medial" is installed in incorrect location

### ISSUE THREAD

**Issue by nbozhkov-ucl** [streamingltd/MEDIAL-Moodle-ATTO#2]
!!! Plugin "tiny_medial" is installed in incorrect location "$CFG-&gt;dirroot/lib/editor/atto/plugins/helixatto", expected location is "$CFG-&gt;dirroot/lib/editor/tiny/plugins/medial" !!!

This seem to be related to the latest version -  https://github.com/streamingltd/MEDIAL-Moodle-ATTO/releases/tag/8.5.10-2024012301-release

**Comment by sharpchi** [comment]
Yes, this plugin has had the Tiny editor plugin code accidentally merged in. The last updates need to be undone.

**Comment by tim1mw** [comment]
Now fixed, that's an oops moment for the release. The Tiny editor is now here where it should have been: https://github.com/streamingltd/MEDIAL-Moodle-Tiny

**Comment by tim1mw** [comment]
Closing
