### ISSUE TITLE
Failed CI/CD phpunit tests due to missing privacy API implementation

### ISSUE THREAD

**Issue by niko-hoogeveen** [streamingltd/MEDIAL-Moodle-ATTO#3]
Missing implementation of privacy/provider.php and lang/en privacy:metadata string to pass the provider_test.php unit test in CI/CD pipeline

**Comment by tim1mw** [comment]
This has now been incorporated in our private development version and will be part of the next release to be pushed to this repository once QA is complete.

**Comment by sharpchi** [comment]
Hi, you missed the privacy:metadata string from the lang file

**Comment by tim1mw** [comment]
I've added privacy:metadata to the private dev version.
